### ISSUE TITLE
Support for AMD modules?

### ISSUE THREAD

**Issue by raDiesle** [tbosch/jasmine-ui#8] opened 2012-06-11 11:07 UTC
Hi,

as you told me before, currently you have to include jasmine tests by <script tags.

Have you thought about support for AMD modules? Do you see any difficulties to add support for it?

How do you think about it general?

Thanks,

David

**Comment by tbosch** [comment] 2012-06-12 17:11
Hi David,
this is not so easy to implement, sorry. The problem is that jasmine-ui needs to detect the location of the scripts that contains the ui tests, as it injects them into the pages to test. In a normal browser, jasmine ui can just look into the dom for the last script in the head-element while a `describe` statement is executed. 
However, with AMD modules the `describe` would be executed at a later point in time than the actual script load. So, if jasmine-ui wants to get the script location of the ui test, it needs to integrate with the AMD loader.

I leave this ticket open as a feature request.

Tobias

**Comment by tbosch** [comment] 2012-08-24 07:48
Hi, 
we are starting a refactoring to support this. See the milestone https://github.com/tigbro/jasmine-ui/issues?milestone=1

Tobias

**Comment by tbosch** [comment] 2013-02-18 16:28
The new project uitest.js does support AMD modules, both, as tests and in the application under test.

Jasmine-Ui has been superseded by uitest.js:
- Github: [https://github.com/tigbro/uitest.js](https://github.com/tigbro/uitest.js)
- Migration-Guide and why: [https://github.com/tigbro/uitest.js/blob/master/docs/jasmineUiMigration.md](https://github.com/tigbro/uitest.js/blob/master/docs/jasmineUiMigration.md).

Closing this as this project is no more active...

**Closed as completed by tbosch** 2013-02-18 16:28 UTC
